### ISSUE TITLE
vzdeploy: wishlist: drop custom MAC generation code

### ISSUE THREAD

**Issue by terrorobe** [sts/ruby-openvz#14]
All MACs can be generated by OpenVZ itself, as seen in: http://git.openvz.org/?p=vzctl;a=blob;f=src/lib/veth.c;h=bded42342106b4151865722890404e101c4b8d5c;hb=HEAD#l184

For example,

```
vzctl set 1000 --save --netif_add vlan300,,,,br_bond0_v300
```

will generate the following NETIF snippet:

```
ifname=vlan300,bridge=br_bond0_v300,mac=00:18:51:2F:68:C6,host_ifname=veth12003.300,host_mac=00:18:51:ED:AB:8D
```

**Comment by sts** [comment]
As Linux software bridges will assume the MAC address of the enslaved interface with the numerically lowest MAC address, this leeds to issues for most of the environments I currently know.

Using it as described above, requires you to hardcode the mac address of your bridge devices in interface configuration. I'm currently rejecting this request.
