### ISSUE TITLE
Not working on Ruby 1.9.2

### ISSUE THREAD

**Issue by mborromeo** [sts/ruby-openvz#3]
Hi!
ruby-openvz doesn't work on Ruby 1.9.2, because of the vendored gem "systemu".
systemu has been patched to work with Ruby 1.9.2 [1], so the vendored gem needs to be updated, or removed from the vendored directory and included into gem deps (but i don't know if there are some customization of systemu in place)

Thanks!

[1] https://github.com/ahoward/systemu/blob/master/lib/systemu.rb#L253

**Comment by sts** [comment]
Hello Marco,

I just replaced the systemu gem from vendored code in branch issue_3. I didn't make a gem release yet.

Maybe you could first verify it fixes your issues on 1.9.1 and I'll try to test other ruby versions. 

Anyways we should probably also start to implement some tests for the library, but I don't have much
experience with rspec.

**Comment by mborromeo** [comment]
Hi Stefan, i'll test the branch asap and i'll let you know!

No worries for the tests, we use this gem a lot to automate some operations, so we'll take care of them!

Sent from my iPhone (but I have fat thumbs so forgive any typos)

Il giorno 08/mag/2012, alle ore 20:30, Stefan Schlesingerreply@reply.github.com ha scritto:

**Comment by mborromeo** [comment]
I had some test, but i don't know why the gem just forks "ruby -e 42" processes in a loop, killing my machine.
I'll dig into this today.

**Comment by mborromeo** [comment]
Not a ruby-openvz issue.
Sounds like something is wrong with systemu gem, which keep spawning ruby processes like "ruby -e 42".

This is the offending line: https://github.com/ahoward/systemu/blob/master/lib/systemu.rb#L31

I'll keep digging.

**Comment by sts** [comment]
Marco, can you already provide me with any updates to this issue?
